LOG_LEVEL: info
MISSION_CONTROL_PORT: 4000
ROS_BRIDGE_URL: ws://localhost:9090
MISSION_CONTROL_HOST: 127.0.0.1
IFACE_NAME: enP1p1s0 #wlP7p1s0
MAC: "3C:6D:66:63:CE:7F" #"58:02:05:0c:a9:9c"
AMR: fork

DEBUG_LOGGER: false
HEARTBEAT_LOGGER: false

RABBIT_MQ_HOST: 127.0.0.1
RABBIT_MQ_PORT: 5672
RABBIT_MQ_USER: kenmec
RABBIT_MQ_PASSWORD: kenmec
RABBIT_MQ_HEARTBEAT: 5000
