export enum ReturnCode {
    SUCCESS = "0000",
    UNDELIVERABLE = "1111",

    MISSION_CONTINUE_LOGIN_SUCCESS = "3000",
    MISSION_NOT_SYNC_LOGIN_SUCCESS = "3001",
    MISSION_TIMEOUT_LOGIN_SUCCESS = "3002",
    MISSION_NOT_SYNC_LOGIN_SUCCESS_WITH_AMR_SERVICE = "3003",

    FORMAT_ERROR_LOGIN_ERROR = "3441",
    NOT_IN_SYSTEM_LOGIN_ERROR = "3442",

    shortestPathServiceFailed = "0001",
    isAllowServiceFailed = "0002",
    IS_ARRIVE_ERROR = "0003",
    IS_AWAY_ERROR = "0005",
    reroutePathServiceFailed = "0006"
}


export const registerReturnCode = [
    ReturnCode.SUCCESS,
    ReturnCode.MISSION_CONTINUE_LOGIN_SUCCESS,
    ReturnCode.MISSION_NOT_SYNC_LOGIN_SUCCESS,
    ReturnCode.MISSION_NOT_SYNC_LOGIN_SUCCESS_WITH_AMR_SERVICE,
    ReturnCode.MISSION_TIMEOUT_LOGIN_SUCCESS,
    ReturnCode.FORMAT_ERROR_LOGIN_ERROR,
    ReturnCode.NOT_IN_SYSTEM_LOGIN_ERROR
]

